### ISSUE TITLE
Template parsing fails wit PHP 7.3

### ISSUE THREAD

**Issue by daniellienert** [jonnitto/Jonnitto.Plyr#22] opened 2019-05-17 15:25 UTC
With PHP 7.3 parsing of the Fluid templated JS files fails with an NamespaceDetectionTemplateProcessor Exception.

See: https://github.com/neos/neos-development-collection/pull/2484

**Comment by jonnitto** [comment] 2019-05-20 11:57
Thanks for your report! Do you want to create a PR?

**Comment by kdambekalns** [comment] 2019-06-19 13:21
That error is fixed by now – but I run into the next now. This is the exception trace [20190619131443ede2c9.txt](https://github.com/jonnitto/Jonnitto.Plyr/files/3306261/20190619131443ede2c9.txt)

AFAICT caused by [`Jonnitto.Plyr/Resources/Private/Templates/Javascript.js`](https://github.com/jonnitto/Jonnitto.Plyr/blob/2.2.18/Resources/Private/Templates/Javascript.js) - that is a weird template!

I'll try to come up with a fix.

**Comment by jonnitto** [comment] 2019-06-19 13:25
Hmm. Let me think about to solve this another way…

**Closed** 2019-06-19 13:40 UTC
